In [40]:
import numpy as np


In [41]:
#ndarray object


x = np.array([1,2,3,4,5])
print(x)

x = np.array([[1,2],[3,4],[5,6]])
print(x)
print(x.shape)#To get dimensions
x.shape = (2,3)  #change dimensions
print(x)


x = np.array([1,2,3,4,5,6], ndmin = 2)
print(x)

x = np.array([1,2,3,4], dtype = complex)
print(x)
print(x.flags)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [42]:
#Empty ndarray obj

x = np.empty([3,3], dtype = np.float)
print(x)

y = np.zeros([3,2], dtype = int)
print(y)

[[0.0000000e+000 6.8181059e-321 2.4703282e-323]
 [1.4020127e-311 0.0000000e+000 3.2381556e-319]
 [1.4020127e-311 0.0000000e+000 2.4703282e-323]]
[[0 0]
 [0 0]
 [0 0]]


In [43]:
#nparray from existing data
x = [1,2,3,4,5]
a = np.asarray(x, dtype = float)
print(a)

s = b'Good Morning' 
a = np.frombuffer(s, dtype = 'S1', count = 5, offset= 1) # count = - 1 to print all
print(a)


x = range(5)
i = iter(x)
a = np.fromiter(i,dtype = float)
print(a)

print(np.arange(10,20,5))


x = np.linspace(10,20, 5, endpoint = False)  #False to exclude last point
print(x)

[1. 2. 3. 4. 5.]
[b'o' b'o' b'd' b' ' b'M']
[0. 1. 2. 3. 4.]
[10 15]
[10. 12. 14. 16. 18.]


In [44]:
#indexing and slicing

# a = np.arange(10) 
# s = slice(2,7,2) 
# print(a[s])

a = np.arange(10) 
b = a[2:7:2] 
print(b)


a = np.arange(10) 
b = a[5] 
print(b)

[2 4 6]
5


In [45]:
#Integer indexing 
#Indexing return a copy whereas slicing presents a version 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)

[1 4 5]


In [46]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print('Our array is:')
print(x)
print('\n')

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols]

print(y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  2]
 [ 9 11]]
